### ISSUE TITLE
Fails to import in Node

### ISSUE THREAD

**Issue by vpzomtrrfrt** [tamtamchik/apple-iap-tools#1]
Attempting to use this module from Node.js doesn't seem to work, as extensionless imports aren't supported.

```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/colin/ait-tr/node_modules/@tamtamchik/apple-iap-tools/dist/ExpirationIntent' imported from /home/colin/ait-tr/node_modules/@tamtamchik/apple-iap-tools/dist/index.js
    at finalizeResolution (internal/modules/esm/resolve.js:276:11)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

From what I can tell, the official solution to this is to use `.js` extensions in imports (see Microsoft/TypeScript#16577)

**Comment by tamtamchik** [comment]
Should be fixed in [1.1.1](https://github.com/tamtamchik/apple-iap-tools/releases/tag/1.1.1).
